language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - make configure
script:
  - make test

jobs:
  include:
    - stage: deploy
      python: 3.9
      deploy:
        provider: script
        script: make docker_build_push
        on:
          branch: master
