language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - make configure
script:
  - make test
deploy:
  provider: script
  script: make docker_build_push
  on:
    branch: docker-build-push
